connectedin/connectedin/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from perfis import views as perfis_views
from usuarios import views as usuarios_views
from django.contrib.auth import views as v
from usuarios.views import RegistrarUsuarioView
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    path('', perfis_views.index,name='index'),
    path('perfil/<int:perfil_id>', perfis_views.exibir_perfil, name='exibir'),
    path('perfil/<int:perfil_id>/convidar',perfis_views.convidar, name='convidar'),
    path('convite/<int:convite_id>/aceitar',perfis_views.aceitar, name='aceitar'),
    path('convite/<int:convite_id>/recusar',perfis_views.recusar, name='recusar'),
    path('perfil/<int:perfil_id>/desfazer', perfis_views.desfazer_amizade, name='desfazer_amizade'),
    path('registrar/', RegistrarUsuarioView.as_view(), name = 'registrar'),
    path('login/', v.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', v.LogoutView.as_view(template_name='login.html'), name='logout'),
    path('desativar_perfil/',perfis_views.desativar_perfil, name='desativar'),
    path('ativar_perfil/', perfis_views.ativar_perfil, name='ativar'),
    path('update_photo/', perfis_views.MudarFotoPerfil, name='update_photo'),
    path('change_password', usuarios_views.ChangePassword, name='change_password'),
    path('novo_post/', perfis_views.novo_post, name='novo_post'),
    path('excluir_post/<int:post_id>', perfis_views.excluir_post, name='exluir_post'),
    path('make_superuser/perfil/<int:perfil_id>', perfis_views.make_superuser, name='make_superuser'),
    path('listar_perfis/', perfis_views.listar_perfis, name='listar_perfis'),
    path('cancelar_solicitacao/<int:perfil_id>', perfis_views.cancelar_solicitacao, name='cancelar_solicitacao'),
    path('bloquear_perfil/<int:perfil_id>', perfis_views.bloquear_contato, name='bloquear_contato'),
    path('desbloquear_perfil/<int:perfil_id>', perfis_views.desbloquear_contato, name='desbloquear_contato'),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

connectedin/usuarios/models.py
from django.db import models

# Create your models here.

connectedin/usuarios/forms.py
from django import forms
from django.forms.utils import ErrorList
from django.contrib.auth.models import User

class RegistrarUsuarioForm(forms.Form):
    nome = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    senha = forms.CharField(required=True)
    telefone = forms.CharField(required=True)
    nome_empresa = forms.CharField(required=True)


    def is_valid(self):
        valid = True
        if not super(RegistrarUsuarioForm, self).is_valid():
            self.adiciona_erro('Por favor, verifique os dados informados')
            valid = False

            user_exists = User.objects.filter(email=self['email']).exists()
            if user_exists:
                self.adiciona_erro('Usuario já existente')
                valid = False

        return valid


    def adiciona_erro(self, message):
        errors = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
        errors.append(message)

connectedin/usuarios/views.py
from django.shortcuts import render, redirect
from usuarios.forms import RegistrarUsuarioForm
from django.contrib.auth.models import User
from perfis.models import Perfil, TimeLine
from django.db import transaction
from django.contrib.auth.decorators import login_required
from django.views.generic.base import View
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages


class RegistrarUsuarioView(View):

    template_name = 'registrar.html'

    def get(self, request):
        return render(request, self.template_name)


    @transaction.atomic()
    def post(self, request):
        form = RegistrarUsuarioForm(request.POST)
        if form.is_valid():
            dados_form = form.cleaned_data
            usuario = User.objects.create_user(username=dados_form['nome'],
                                               email=dados_form['email'],
                                               password=dados_form['senha'])

            perfil = Perfil(nome=dados_form['nome'],
                            telefone=dados_form['telefone'],
                            nome_empresa=dados_form['nome_empresa'],
                            usuario=usuario)
            perfil.save()

            timeline = TimeLine(perfil_id=perfil.id)
            timeline.save()

            return redirect('index')

        return render(request, self.template_name, {'form':form})


@login_required()
@transaction.atomic()
def ChangePassword(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, 'Nova senha cadastrada')
            return redirect('index')

    if request.method == 'GET':
        form = PasswordChangeForm(user=request.user)
        args = {'form': form}

        return render(request, 'change_password.html', args)

connectedin/usuarios/templates/base_usuario.html
{% load staticfiles %}
<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="{% static 'styles/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'styles/signin.css' %}" rel="stylesheet">
    <title>ConnectedIn</title>
</head>
<body>
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
</body>
</html>

connectedin/usuarios/templates/change_password.html
{% extends 'base_usuario.html' %}
{% block body %}
    <div class="container">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="button btn-primary">Salvar</button>
        </form>
    </div>
{% endblock %}

connectedin/usuarios/templates/login.html
{% extends "base_usuario.html" %}
{% block body %}
<form class="form-signin" role="form" action="{% url 'login' %}" method="post">
    {% csrf_token %}
    <h2 class="form-signin-heading">Login</h2>
    <input id="id_username" name="username" class="form-control" placeholder="Nome" required autofocus>

    <input type="password" id="id_password" name="password" class="form-control" placeholder="Senha" required>

    <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Login</button>

    {% if form.errors %}
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        Por favor, verifique o Email e/ou Senha informados
    </div>
    {% endif %}
    <a href="{% url 'registrar' %}">Registre-se</a>
    <br/>
    <a href="#">Esqueceu sua senha?</a>
    <br/><br/>
    <a href="{% url 'ativar' %}">Reativar conta</a>
</form>
{% endblock %}

connectedin/usuarios/templates/registrar.html
{% extends 'base_usuario.html' %}
{% block body %}
    <form class="form-signin" action="{% url 'registrar' %}" method="post">
        {% csrf_token %}
        <h2 class="form-signin-heading">Crie seu Usuário</h2 >
        <input id="id_email" name="email" class="form-control" placeholder="Email *" required autofocus>
        <input id="id_nome" name="nome" class="form-control" placeholder="Nome *" required>
        <input type="password" id="id_senha" name="senha" class="form-control" placeholder="Senha *" required>
        <hr/>
        <input id="id_telefone" name="telefone" class="form-control" placeholder="Telefone" required>
        <input id="id_nome_empresa" name="nome_empresa" class="form-control" placeholder="Empresa" required>
        <hr/>
        <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Registrar</button>

        {% if form.errors %}
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
                {{ form.non_field_errors }}
            </div>
        {% endif %}
    </form>
{% endblock %}